const express = require('express');
const router = express.Router();
const { createUser,loginUser,logoutUser,activateUser,resendActivation } = require('../controllers/auth.controller');
const { validateUserRules,validateLoginRules, validateUser } = require('../middleware/validators/authValidators');
router.post('/register', validateUserRules, validateUser, createUser);
router.post('/login',validateLoginRules,loginUser); 
router.post('/logout', logoutUser);
router.get('/activate/:userId/:token', activateUser);
router.post('/resend-activation', resendActivation);
module.exports = router;
